
platform :ios, '8.0'
inhibit_all_warnings!

#source 'https://git.coding.net/CocoaPods/Specs.git'

target 'DisaterInformation' do
 
pod 'Masonry', '~> 1.0.0'
pod 'SDAutoLayout', '~> 2.1.1'
pod 'IQKeyboardManager', '~> 4.0.8'

end

